#include "hardware/pio.h"
#include "hardware/clocks.h"            // for clock_get_hz() in generated header
#include "seven_segment_library.pio.h"      // generated by pioasm

bool seven_segment_init (PIO pio, uint *p_sm, uint gpio);
