#include "hardware/pio.h"
#include "hardware/clocks.h"                // for clock_get_hz() in generated header
#include "seven_segment_library.pio.h"      // generated by pioasm

uint32_t num_to_seven_segment (int num);
bool seven_segment_init (PIO pio, uint *p_sm, uint segment_pinbase, uint digit_pinbase);
